import React from "react";

export default function Client() {
  return (
   
        <section className="bg-dark vh-30 p-5 mb-5 align-items-center" data-aos="fade-up" data-aos-duration="2000">
          <marquee behavior="scroll" direction="left" hspace="10%">
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} /> 
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} /> 
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
            <img src="favicon.ico" width="300" height="200" alt="Company" style={{padding:20}} />
          </marquee>
        </section>
         )}